yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('about/', include('about.urls', namespace='about')),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view
        (template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

LINE_NUMBER = 15

User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name="Текст",
                            help_text='заполните это поле')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name="Группа",
        help_text='заполните это поле'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:LINE_NUMBER]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField('slug', unique=True, )
    description = models.TextField()

    def __str__(self):
        return self.title[:LINE_NUMBER]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


from .forms import PostForm
from .models import Group, Post, User

POST_NUMBER = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POST_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, POST_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': post_list,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_posts = author.posts.select_related('author')
    post_count = author_posts.count()
    paginator = Paginator(author_posts, POST_NUMBER)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'post_count': post_count,
        'page_obj': page_obj
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    pub_date = post.pub_date
    post_title = post.text[:30]
    author = post.author
    author_post = author.posts.all().count()
    context = {
        "post": post,
        "post_title": post_title,
        "pub_date": pub_date,
        "author": author,
        "author_post": author_post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/create_post.html', {'form': form})


def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    if request.user != author:
        return redirect('posts:post_detail', post_id)
    elif request.user == author:
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            post.save()
            return redirect('posts:post_detail', post_id)
        context = {'form': form, 'post': post}
        return render(request, 'posts/create_post.html', context)
    context = {
        'form': form,
        'post': post,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="container col-lg-9 col-sm-12">
  <h4>Привет, я Полина Горшкова и я начинающий разработчик</h4>
  <img src="{% static 'img/cat_pr.png' %}" width="30%" height="30%">


  <p>
    Пока что это мой первый сайт и я надеюсь не последний...
  </p>
  <p>
      Я только учусь и думаю у меня все получится. Мир IT очень интересный и многообразный и рада стать его частью!
  </p>
  </div>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h4>Вот что я умею</h4>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>Технологии</p>
      <p> В ходе данного проекта ,я научилась создавать сайт при помощи django.
        Создавать форму регистрации с помощью UserCreationForm . Узнала что такое paginator и 'с чем его едят'.
        И еще много всего интересного!
    </article>
  </div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">   
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header> 
      {% include 'includes/header.html' %}     
    </header> 
    <main> 
      {% block content %}
      {% endblock %}  
    </main>  
    <footer> 
      {% include 'includes/footer.html' %}    
    </footer>     
  </body>

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'about:author' %}active {% endif %}"
           href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active {% endif %}"
           href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link  {% if view_name == 'posts:post_create' %}active {% endif %}"
             href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:password_reset_form' %}active {% endif %}"
             href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
             href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
</header>
{% endwith %}

yatube/templates/includes/paginator.html
{% load static %}
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Новый пост 
{% else %}
  Редактировать
{% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
              {% if is_edit %}
                Редактировать
              {% else %}
                Новый пост 
              {% endif %}            
              </div>
              <div class="card-body">        
                {% if is_edit %}
                  <form method="POST" enctype="multipart/form-data"
                  action="{% url 'posts:post_edit' post.id %}">{% csrf_token %}
                {% else %}
                  <form method="POST" enctype="multipart/form-data"
                  action="{% url 'posts:post_create' %}">{% csrf_token %}
                {% endif %}
                {% load user_filters %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                     <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}
                        <span class="required text-danger" >*</span>
                        {% endif %}
                      </label>
                      {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                     {% endif %}
                   </div>
                {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
   {{group.title}}
{% endblock %}
{% block content %}
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
          {% for post in posts %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>      
              <p>
                {{ post.text }}
              </p>         
            </article>
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
   yatube
{% endblock %}
{% block content %}
   <h1> Главная страница </h1>
   {% for post in page_obj %}
      <article>
         <ul>
           <li>
             Автор: {{ post.author.get_full_name }}
           </li>
           <li>
             Дата публикации: {{ post.pub_date|date:"d E Y" }}
           </li>
         </ul>      
         <p>{{ post.text|linebreaksbr}}</p>
         {% if post.group %}  
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
         {% endif %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
   {% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post_title|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <main>
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
           {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }} {{ author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span>{{ author_posts }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if user.username == post.author.username %}
            <a class="btn btn-primary" href = "{% url 'posts:post_edit' post.pk %}">
              Редактировать запись
            </a>
          {% endif %}
        </article>
       </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ posts_count }} </h3>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }} 
              </li>
            </ul>
            <p>
            {{ post.text }} 
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
          </article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
          {% if not forloop.last %}       
          <hr>
          {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}  
      </div>
{% endblock %}

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/login.html
# templates/users/login.html

{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
<!DOCTYPE html> 
{% load static %}
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Сброс пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="../users/password_reset_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/signup.html
<!-- templates/users/signup.html -->

{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}